name: BuildingServer
version: '${version}'
main: net.turniptales.buildingserver.BuildingServer
api-version: '1.21.1'
description: A plugin for the TurnipTales Building server
website: https://turniptales.net/
